import Head from "next/head";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hanting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keyword" content="next, hunting blog, hunting coder" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.imagewarp}>
          <img
            className={styles.myimg}
            src="/homeimg.avif"
            width={237}
            height={158}
            alt="hunting coder"
          />
        </div>
        <h1 className={styles.title}>
          <span className="myspan dummy">&lt;Hunting coder/&gt;</span>
        </h1>
        <p className={styles.description}>
          A blog for hunting coders by a hunting Coder
        </p>
        <div className={styles.blog}>
          <h2>Letest blogs</h2>
          <div>
            <h3 className={styles.h3}>How to larn javascript in 2023 ?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
            <button className={styles.btn}></button>
          </div>
          <div>
            <h3 className={styles.h3}>How to larn reactjs in 2023 ?</h3>
            <p>reactjs is the language used to design logic for the web</p>
            <button className={styles.btn}></button>
          </div>
          <div>
            <h3 className={styles.h3}>How to larn nextjs in 2023 ?</h3>
            <p>nextjs is the language used to design logic for the web</p>
            <button className={styles.btn}></button>
          </div>
        </div>
      </main>
    </>
  );
}
